name: Set up Gradle Action
description: Sets up Gradle Action
runs:
  using: "composite"
  steps:
    - name: Setup Gradle Build Action
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-home-cache-includes: |
          caches
          notifications
          jdks
